### ISSUE TITLE
Plugin is too awesome.

### ISSUE THREAD

**Issue by spdustin** [dflydev/embed-github-gist#8]
Quick, well executed, and flawless in multisite. Yeah, I raised an issue to tell you that. Hope you see that as a good thing. :)

**Comment by simensen** [comment]
@spdustin thanks. :) has been a rough few days with the new changes github made to gist so i'm happy it is still making someone happy. :)

**Comment by spdustin** [comment]
I bet - the changes caught me in the middle of a live class! :grin:

**Comment by niyazpk** [comment]
+1
